name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0, v2.1.3)

permissions:
  contents: write
  discussions: write

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
            arch: x64
            ext: .exe
          - os: windows-latest
            platform: win
            arch: arm64
            ext: .exe
          - os: macos-latest
            platform: mac
            arch: universal
            ext: .dmg
          - os: ubuntu-latest
            platform: linux
            arch: x64
            ext: .AppImage
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            ext: .AppImage

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv (Python package manager)
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
            echo "$env:USERPROFILE\.cargo\bin" >> $GITHUB_PATH
          else
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          fi
        shell: bash

      - name: Install Python dependencies
        run: |
          cd python_backend
          uv sync
        shell: bash

      - name: Install Node.js dependencies
        run: |
          cd mcp-ai-desktop
          pnpm install

      - name: Build Electron app
        run: |
          cd mcp-ai-desktop
          pnpm run dist -- --${{ matrix.platform }} --${{ matrix.arch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer-${{ matrix.arch }}
          path: |
            mcp-ai-desktop/dist/*.exe
            mcp-ai-desktop/dist/*.msi

      - name: Upload macOS artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: |
            mcp-ai-desktop/dist/*.dmg
            mcp-ai-desktop/dist/*.zip

      - name: Upload Linux artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-installer-${{ matrix.arch }}
          path: |
            mcp-ai-desktop/dist/*.AppImage
            mcp-ai-desktop/dist/*.deb
            mcp-ai-desktop/dist/*.rpm

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Display structure of downloaded files
        run: |
          echo "=== Artifacts structure ==="
          find ./artifacts -type f -name "*" | sort
          echo "=========================="

      - name: Prepare release files
        run: |
          mkdir -p ./release-files

          # Copy all files to a flat structure for easier uploading
          if [ -d "./artifacts/windows-installer-x64" ]; then
            cp ./artifacts/windows-installer-x64/* ./release-files/ 2>/dev/null || true
          fi

          if [ -d "./artifacts/windows-installer-arm64" ]; then
            cp ./artifacts/windows-installer-arm64/* ./release-files/ 2>/dev/null || true
          fi

          if [ -d "./artifacts/macos-installer" ]; then
            cp ./artifacts/macos-installer/* ./release-files/ 2>/dev/null || true
          fi

          if [ -d "./artifacts/linux-installer-x64" ]; then
            cp ./artifacts/linux-installer-x64/* ./release-files/ 2>/dev/null || true
          fi

          if [ -d "./artifacts/linux-installer-arm64" ]; then
            cp ./artifacts/linux-installer-arm64/* ./release-files/ 2>/dev/null || true
          fi

          echo "=== Release files prepared ==="
          ls -la ./release-files/
          echo "=============================="

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}

            ## Downloads

            ### Windows
            - Download the `.exe` installer for Windows (x64)
            - Download the `.exe` installer for Windows (ARM64)

            ### macOS
            - Download the `.dmg` installer for macOS

            ### Linux
            - Download the `.AppImage` for portable Linux installation (x64)
            - Download the `.AppImage` for portable Linux installation (ARM64)
            - Download the `.deb` package for Debian/Ubuntu (x64)
            - Download the `.deb` package for Debian/Ubuntu (ARM64)
            - Download the `.rpm` package for Red Hat/Fedora (x64)
            - Download the `.rpm` package for Red Hat/Fedora (ARM64)

          draft: false
          prerelease: false
          files: ./release-files/*
          fail_on_unmatched_files: false
